name: 'telecom_dbt'
version: '1.0.0'
profile: 'telecom_dbt'

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  telecom_dbt:
    staging:
      +materialized: view
      +schema: DATA_STAGING
    marts:
      +materialized: table
      +schema: DATA_MARTS