[project]
name = "practice-snowflake-dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dbt-snowflake>=1.12.1",
]

[project.scripts]
practice-snowflake-dbt = "practice_snowflake_dbt:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
